#!/bin/bash
echo "================================"
echo "True Home Web Deployment Script"
echo "================================"
echo ""
echo "✅ Web build ready at: build/web"
echo ""
echo "To deploy, run these commands:"
echo ""
echo "1. Firebase login (on your machine with browser access):"
echo "   firebase login"
echo ""
echo "2. Deploy the web build:"
echo "   firebase deploy --only hosting"
echo ""
echo "OR upload the build/web folder contents to Firebase Console:"
echo "   https://console.firebase.google.com/u/0/project/truehome-9a244/hosting"
echo ""
