#!/bin/bash
echo "========================================="
echo "TrueHome App Icon Setup"
echo "========================================="
echo ""
echo "Steps to complete:"
echo ""
echo "1. Right-click the TrueHome logo image in your chat"
echo "2. Save it as: assets/images/app_icon.png"
echo "3. Copy it again as: assets/images/app_icon_foreground.png"
echo ""
echo "Then run:"
echo "  flutter pub get"
echo "  dart run flutter_launcher_icons"
echo ""
echo "Checking current assets folder..."
ls -la assets/images/ | head -20
echo ""
echo "Ready to generate icons once you save the image!"
