// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfGVLb-tBvyXpfQLzi-Rw3oP1taV145wY',
    appId: '1:843422990018:android:19395b0ae931a98498455b',
    messagingSenderId: '843422990018',
    projectId: 'truehome-9a244',
    storageBucket: 'truehome-9a244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8OE87qRxsyqC0A5_Yxwb0jLLzVBMICs',
    appId: '1:843422990018:ios:1089546551b0fda898455b',
    messagingSenderId: '843422990018',
    projectId: 'truehome-9a244',
    storageBucket: 'truehome-9a244.firebasestorage.app',
    iosBundleId: 'com.example.trueHome',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfGVLb-tBvyXpfQLzi-Rw3oP1taV145wY',
    appId: '1:843422990018:web:19395b0ae931a98498455b',
    messagingSenderId: '843422990018',
    projectId: 'truehome-9a244',
    authDomain: 'truehome-9a244.firebaseapp.com',
    storageBucket: 'truehome-9a244.firebasestorage.app',
  );
}
